#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

//defined('YII_DEBUG') or define('YII_DEBUG', true);
//defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
// Environment
require(__DIR__ . '/env.php');
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/common/config/bootstrap.php';

$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/common/config/main.php',
    require __DIR__ . '/common/config/main-local.php',
    require __DIR__ . '/console/config/main.php'
);

//全局方法
include_once __DIR__ . '/common/helpers/function.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
